# Generated by Django 4.2.13 on 2024-11-26 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_result_test_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.DeleteModel(
            name='chat_data',
        ),
        migrations.DeleteModel(
            name='contacts',
        ),
        migrations.DeleteModel(
            name='earnings',
        ),
        migrations.DeleteModel(
            name='email_verify',
        ),
        migrations.DeleteModel(
            name='fake_proof_reports',
        ),
        migrations.DeleteModel(
            name='jobs',
        ),
        migrations.DeleteModel(
            name='jobs_proofs',
        ),
        migrations.DeleteModel(
            name='notifications',
        ),
        migrations.DeleteModel(
            name='payment_history',
        ),
        migrations.DeleteModel(
            name='posts',
        ),
        migrations.RemoveField(
            model_name='question',
            name='test',
        ),
        migrations.DeleteModel(
            name='referals',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
        migrations.RemoveField(
            model_name='subcategories',
            name='belongs_to',
        ),
        migrations.DeleteModel(
            name='user_details',
        ),
        migrations.DeleteModel(
            name='withdraw',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='categories',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='subcategories',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
