# Generated by Django 4.2.13 on 2024-11-26 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0033_remove_answer_question_delete_chat_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('niche', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_no', models.CharField(editable=False, max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('time', models.TimeField()),
                ('video_type', models.CharField(choices=[('Long', 'Long'), ('Short', 'Short'), ('Reel', 'Reel'), ('Pic Only', 'Pic Only')], max_length=10)),
                ('platform', models.CharField(choices=[('YouTube', 'YouTube'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('TikTok', 'TikTok'), ('LinkedIn', 'LinkedIn'), ('X', 'X'), ('Threads', 'Threads'), ('Pinterest', 'Pinterest')], max_length=15)),
                ('orientation', models.CharField(choices=[('Landscape', 'Landscape'), ('Portrait', 'Portrait')], max_length=10)),
                ('description', models.TextField()),
                ('no_of_scenes', models.PositiveIntegerField()),
                ('keywords_driven', models.BooleanField(default=False)),
                ('promo_message', models.TextField(blank=True, null=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postings', to='home.blog')),
            ],
        ),
    ]
