# Generated by Django 4.2.13 on 2024-11-27 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refinement_number', models.PositiveIntegerField()),
                ('refinement_text', models.TextField(blank=True, null=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='home.blog')),
            ],
            options={
                'ordering': ['refinement_number'],
                'unique_together': {('blog', 'refinement_number')},
            },
        ),
    ]
