# Generated by Django 4.2.13 on 2024-11-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_thread'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processing', models.BooleanField(default=False)),
                ('default_keywords', models.TextField(blank=True, null=True)),
                ('default_prompts', models.TextField(blank=True, null=True)),
                ('date_keywords', models.TextField(blank=True, null=True)),
                ('date_prompts', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
