# Generated by Django 4.2.13 on 2024-12-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_commonprompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='unique_identifier',
            field=models.CharField(blank=True, default='nice123', max_length=50, null=True, unique=True),
        ),
    ]
