# Generated by Django 4.2.13 on 2024-12-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_blog_unique_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='priority',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
