# Generated by Django 4.2.13 on 2024-12-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_alter_blog_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='refinement_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
