# Generated by Django 4.2.13 on 2024-12-27 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_thread_refinement_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prompts',
            old_name='prompt_data',
            new_name='prompts',
        ),
    ]
