# Generated by Django 4.2.13 on 2024-12-28 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_rename_prompt_data_prompts_prompts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('field_type', models.CharField(choices=[('number', 'Number'), ('text', 'Text'), ('textarea', 'Description')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraFieldData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='home.extrafield')),
            ],
        ),
    ]
