# Generated by Django 4.2.13 on 2025-01-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_extrafield_extrafielddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='gpt_api_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
