# Generated by Django 4.2.13 on 2025-01-01 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_config_gpt_api_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='gpt_api_key',
        ),
    ]
