# Generated by Django 4.2.13 on 2025-01-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_remove_config_gpt_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='openai_thread_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
