# Generated by Django 4.2.13 on 2025-01-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_blog_openai_thread_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='hook_scene',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='refined_scenes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='scenes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='scripts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='storyline',
            field=models.TextField(blank=True, null=True),
        ),
    ]
