# Generated by Django 4.2.13 on 2025-01-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_blog_hook_scene_blog_refined_scenes_blog_scenes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='animation_instructions_scenes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='dale_ai_scenes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='dale_images',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='refine_dale_ai_scenes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='refined_ssml_scenes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='social_media_scenes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='ssml_scenes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='wav_srt_scenes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
