# Generated by Django 4.2.13 on 2025-01-04 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_blog_animation_instructions_scenes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='posting_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
