# Generated by Django 4.2.13 on 2025-01-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_posting_posting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='animation_instructions_scenes',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='dale_ai_scenes',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='dale_images',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='hook_scene',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='refine_dale_ai_scenes',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='refined_scenes',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='refined_ssml_scenes',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='scenes',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='scripts',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='social_media_scenes',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='ssml_scenes',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='wav_srt_scenes',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
    ]
