# Generated by Django 4.2.13 on 2025-01-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_alter_blog_animation_instructions_scenes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='animation_instructions_scenes',
            field=models.TextField(blank=True, default='{"animation_instructions":[]}', null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='dale_ai_scenes',
            field=models.TextField(blank=True, default='{"dale_prompts":[]}', null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='dale_images',
            field=models.TextField(blank=True, default='{"dale_images":[]}', null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='refine_dale_ai_scenes',
            field=models.TextField(blank=True, default='{"refined_dale_prompts":[]}', null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='refined_scenes',
            field=models.TextField(blank=True, default='{"refined_scripts":[]}', null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='refined_ssml_scenes',
            field=models.TextField(blank=True, default='{"refined_ssml_scripts":[]}', null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='scenes',
            field=models.TextField(blank=True, default='{"scenes":[]}', null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='scripts',
            field=models.TextField(blank=True, default='{"scripts":[]}', null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='social_media_scenes',
            field=models.TextField(blank=True, default='{"social_media":[]}', null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='ssml_scenes',
            field=models.TextField(blank=True, default='{"ssml_scripts":[]}', null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='wav_srt_scenes',
            field=models.TextField(blank=True, default='{"media_files":[]}', null=True),
        ),
    ]
