# Generated by Django 4.2.13 on 2025-01-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='priority',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=5),
        ),
    ]
