# Generated by Django 4.2.13 on 2025-06-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_alter_blog_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('short_description', models.TextField(max_length=300)),
                ('full_description', models.TextField()),
                ('features', models.TextField(help_text='Enter features separated by new lines')),
                ('main_image', models.ImageField(upload_to='extensions/images/')),
                ('screenshot_1', models.ImageField(blank=True, null=True, upload_to='extensions/screenshots/')),
                ('screenshot_2', models.ImageField(blank=True, null=True, upload_to='extensions/screenshots/')),
                ('screenshot_3', models.ImageField(blank=True, null=True, upload_to='extensions/screenshots/')),
                ('chrome_store_url', models.URLField()),
                ('how_to_use', models.TextField()),
                ('installation_guide', models.TextField()),
                ('faq', models.TextField(blank=True, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('privacy_policy', models.TextField()),
                ('terms_of_service', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
            ],
            options={
                'ordering': ['-featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Chrome Extensions Hub', max_length=100)),
                ('site_description', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('support_email', models.EmailField(max_length=254)),
                ('general_privacy_policy', models.TextField()),
                ('general_terms_of_service', models.TextField()),
                ('about_us', models.TextField()),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.DeleteModel(
            name='CommonPrompt',
        ),
        migrations.DeleteModel(
            name='Config',
        ),
        migrations.RemoveField(
            model_name='extrafielddata',
            name='field',
        ),
        migrations.RemoveField(
            model_name='posting',
            name='blog',
        ),
        migrations.DeleteModel(
            name='Prompts',
        ),
        migrations.AlterUniqueTogether(
            name='thread',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='thread',
            name='blog',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='ExtraField',
        ),
        migrations.DeleteModel(
            name='ExtraFieldData',
        ),
        migrations.DeleteModel(
            name='Posting',
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
