# Generated by Django 4.2.13 on 2025-06-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_extension_sitesettings_delete_commonprompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extension',
            name='youtube_video_url',
            field=models.URLField(blank=True, help_text='YouTube video URL (e.g., https://www.youtube.com/watch?v=VIDEO_ID or https://youtu.be/VIDEO_ID)', null=True),
        ),
        migrations.AlterField(
            model_name='extension',
            name='faq',
            field=models.TextField(blank=True, help_text='Use Q: and A: format OR HTML formatting', null=True),
        ),
        migrations.AlterField(
            model_name='extension',
            name='features',
            field=models.TextField(help_text='Enter features separated by new lines OR use HTML formatting'),
        ),
        migrations.AlterField(
            model_name='extension',
            name='full_description',
            field=models.TextField(help_text='HTML formatting supported'),
        ),
        migrations.AlterField(
            model_name='extension',
            name='how_to_use',
            field=models.TextField(help_text='HTML formatting supported'),
        ),
        migrations.AlterField(
            model_name='extension',
            name='installation_guide',
            field=models.TextField(help_text='HTML formatting supported'),
        ),
        migrations.AlterField(
            model_name='extension',
            name='privacy_policy',
            field=models.TextField(help_text='HTML formatting supported'),
        ),
        migrations.AlterField(
            model_name='extension',
            name='terms_of_service',
            field=models.TextField(help_text='HTML formatting supported'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_us',
            field=models.TextField(help_text='HTML formatting supported'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.TextField(blank=True, help_text='HTML formatting supported'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='general_privacy_policy',
            field=models.TextField(help_text='HTML formatting supported'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='general_terms_of_service',
            field=models.TextField(help_text='HTML formatting supported'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_description',
            field=models.TextField(help_text='HTML formatting supported'),
        ),
    ]
