# Generated by Django 4.2.13 on 2025-06-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_extension_youtube_video_url_alter_extension_faq_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extension',
            name='features',
        ),
        migrations.RemoveField(
            model_name='extension',
            name='how_to_use',
        ),
        migrations.RemoveField(
            model_name='extension',
            name='installation_guide',
        ),
        migrations.AlterField(
            model_name='extension',
            name='full_description',
            field=models.TextField(help_text='HTML formatting supported - You can include features, how-to-use, installation guide, and any other content here using HTML'),
        ),
    ]
