# Generated by Django 4.2.13 on 2025-06-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_remove_extension_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extension',
            name='meta_description',
            field=models.CharField(blank=True, max_length=1000000000000000000),
        ),
        migrations.AlterField(
            model_name='extension',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=1000000000000000000000),
        ),
    ]
