# Generated by Django 4.2.13 on 2025-07-08 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0057_alter_extension_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extension',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='extension',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='SEO optimized blog title', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from title', unique=True)),
                ('content', models.TextField(help_text='Full HTML formatting supported - You can copy/paste from Word with images and formatting')),
                ('excerpt', models.TextField(help_text='Short description for blog listing and social media', max_length=300)),
                ('meta_title', models.CharField(blank=True, help_text='SEO title (60 chars max) - Leave blank to use main title', max_length=60)),
                ('meta_description', models.TextField(help_text='SEO meta description (160 chars max)', max_length=160)),
                ('meta_keywords', models.TextField(help_text='SEO keywords separated by commas (as many as needed)')),
                ('featured_image', models.ImageField(help_text='Main blog image for listings and social media', upload_to='blog/images/')),
                ('featured_image_alt', models.CharField(blank=True, help_text='Alt text for featured image (SEO)', max_length=100)),
                ('is_published', models.BooleanField(default=False, help_text='Publish this blog post')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this blog on homepage')),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('canonical_url', models.URLField(blank=True, help_text='Canonical URL if this content exists elsewhere')),
                ('og_title', models.CharField(blank=True, help_text='Open Graph title for social media', max_length=100)),
                ('og_description', models.TextField(blank=True, help_text='Open Graph description for social media', max_length=200)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('related_extension', models.ForeignKey(blank=True, help_text='Link this blog to a specific extension', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.extension')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-is_featured', '-publish_date'],
            },
        ),
    ]
