# Generated by Django 4.2.13 on 2025-07-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_alter_extension_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(help_text='Short description for blog listing and social media', max_length=200000),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image_alt',
            field=models.CharField(blank=True, help_text='Alt text for featured image (SEO)', max_length=200000),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_description',
            field=models.TextField(help_text='SEO meta description (160 chars max)', max_length=200000),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title (60 chars max) - Leave blank to use main title', max_length=200000),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='og_description',
            field=models.TextField(blank=True, help_text='Open Graph description for social media', max_length=200000),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph title for social media', max_length=200000),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(help_text='SEO optimized blog title', max_length=200000),
        ),
    ]
