# Generated by Django 4.2.13 on 2025-07-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_alter_blogpost_excerpt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extension',
            name='meta_description',
            field=models.CharField(blank=True, max_length=2550000),
        ),
        migrations.AlterField(
            model_name='extension',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=2550000),
        ),
        migrations.AlterField(
            model_name='extension',
            name='short_description',
            field=models.TextField(max_length=2550000),
        ),
        migrations.AlterField(
            model_name='extension',
            name='title',
            field=models.CharField(max_length=2550000),
        ),
    ]
